index:
  slogan:
    enable: true
    text: 墨染江河的小窩
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

about:
  avatar: \images\icon\profile.png
  name: "墨染江河"
  intro: "採菊東籬下，悠然見南山。"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/Moranjianghe', tip: 'GitHub' }
    - { class: 'iconfont icon-twitter-fill', link: 'https://twitter.com/moranjianghe', tip: '推特' }
    - { class: 'iconfont icon-note', link: 'https://www.moranxia.com/', tip: '主頁' }
    - { class: 'iconfont icon-telegram-fill', link: 'https://t.me/ink_dyeing', tip: 'Telegram' }
  #  - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }

# 用于浏览器标签的图标
# Icon for browser tab
favicon: /images/icon/noun-ink-bottle-5605401.svg
apple_touch_icon: /images/icon/noun-ink-bottle-5605401.svg

post:
  comments:
    enable: true
    type: disqus

disqus:
  shortname: ink-bottle