index:
  slogan:
    enable: true
    text: 墨染江河的小窩
    api:
      enable: false
      url: "https://v1.hitokoto.cn/"
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

about:
  avatar: \images\icon\profile.png
  name: "墨染江河"
  intro: "採菊東籬下，悠然見南山。"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/Moranjianghe', tip: 'GitHub' }
    - { class: 'iconfont icon-twitter-fill', link: 'https://twitter.com/moranjianghe', tip: '推特' }
    - { class: 'iconfont icon-note', link: 'https://www.moranxia.com/', tip: '主頁' }
    - { class: 'iconfont icon-telegram-fill', link: 'https://t.me/ink_dyeing', tip: 'Telegram' }
  #  - { class: 'iconfont icon-wechat-fill', qrcode: '/img/favicon.png' }

# 用于浏览器标签的图标
# Icon for browser tab
favicon: images/icon/noun-ink-bottle-5605401.svg
apple_touch_icon: images/icon/noun-ink-bottle-5605401.svg

post:
  comments:
    enable: true
    type: disqus

disqus:
  shortname: ink-bottle

# 导航栏的相关配置
# Navigation bar
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title: "墨水瓶"

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
   # - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    #- { key: "links", link: "/links/", icon: "iconfont icon-link-fill" }
    - { key: "links", link: "/atom.xml/", icon: "iconfont icon-rss-fill",name:'RSS' }
    